<div class="w-full max-w-8xl mx-auto h-16 flex justify-between items-center">
  <div class="flex justify-start items-center">
    <a href="/" class="group flex items-center gap-3">
      <img src="/public/assets/img/wisteria.PNG" class="h-10 w-auto transition-transform group-active:scale-95">
    </a>
  </div>

  <div class="flex items-center gap-4">
    <? if (!$this->auth->isAuth()): ?>
      <a href="/auth"
        class="hidden md:flex items-center gap-2 bg-purple-400 hover:bg-purple-400/50 px-6 py-2 rounded text-xs font-bold uppercase tracking-[0.1rem] transition-all duration-200 hover:shadow-full-xl hover:shadow-purple-400/75 hover:ring hover:ring-purple-400/75 backdrop-blur-xs active:scale-95 cursor-pointer hover:text-white">
        <span>Войти</span>
      </a>

      <a href="/auth"
        class="md:hidden flex justify-center items-center w-11 h-11 bg-violet-600/10 border border-violet-500/30 rounded-lg text-violet-400 backdrop-blur-xs">
        <i class="fa-duotone fa-regular fa-arrow-right-to-bracket"></i>
      </a>
    <? else: ?>
      <button id="ddAvatarToggle"
        class="size-12 border border-violet-400/50 rounded-lg relative overflow-hidden cursor-pointer"
        type="button">
        <div class="absolute inset-0">
          <img src="/skin/api/index?mode=mini">
        </div>
      </button>
      <div id="ddAvatarMenu" class="z-20 hidden max-w-sm w-full px-2 transition-opacity duration-200">
        <div
          class="bg-zinc-950/75 backdrop-blur-sm border border-zinc-600 shadow-md shadow-zinc-600/50 p-4 rounded-2xl flex flex-col gap-4">
          <div class="flex items-center gap-4">
            <div>
              <div class="rounded-lg ring ring-zinc-600 overflow-hidden size-12">
                <img src="/skin/api/index?mode=mini" class="size-full">
              </div>
            </div>
            <div>
              <div class="tracking-wide font-semibold text-2xl">
                <?= $this->auth->getUser()->login; ?>
              </div>
              <div class="h-0.5 w-10 bg-violet-400 shadow-full-sm shadow-violet-400 rounded-full"></div>
            </div>
          </div>
          <div class="grid grid-cols-2 md:flex gap-4">
            <a href="/profile"
              class="flex items-center justify-center h-10 hover:shadow-full-sm hover:shadow-purple-400/50 border border-zinc-600 rounded-xl text-2xs md:text-[1rem] uppercase tracking-wider cursor-pointer transition-all md:flex-1 hover:text-purple-400 hover:border-purple-400/75 duration-200">
              <span>Кабинет</span>
            </a>
            <button id="logout"
              class="flex items-center justify-center h-10 border border-zinc-600 hover:border-red-400/75 hover:text-red-400 hover:shadow-full-sm hover:shadow-red-400/50 rounded-xl text-2xs md:text-lg font-semibold uppercase tracking-widest cursor-pointer transition-all md:size-10 duration-200">
              <span class="hidden md:block">
                <i class="fa-duotone fa-regular fa-arrow-right-from-bracket"></i>
              </span>
              <span class="md:hidden">Выйти</span>
            </button>
          </div>
        </div>
      </div>
    <? endif; ?>

    <!-- <button id="drawer-toggle-button"
                class="md:hidden flex justify-center items-center size-10 bg-white/10 hover:bg-white/20 border border-white/10 rounded-lg transition-all group backdrop-blur-xs cursor-pointer"
                type="button">
                <div class="flex flex-col gap-1 items-end">
                    <div class="w-5 h-0.5 bg-violet-400 rounded-full transition-all group-hover:w-6"></div>
                    <div class="w-6 h-0.5 bg-violet-400/50 rounded-full"></div>
                    <div class="w-4 h-0.5 bg-violet-400 rounded-full transition-all group-hover:w-6"></div>
                </div>
            </button> -->
  </div>
</div>