<div class="">
    <div class="flex flex-col gap-2">
        <a href="/profile"
            class="hover:outline hover:outline-zinc-800/75 rounded-[0.5rem] text-sm p-2 text-zinc-400 space-x-1">
            <i class="fa-regular fa-user"></i>
            <span class="hidden md:inline-flex">Мой профиль</span>
        </a>
        <a href="/?router=profile"
            class="hidden hover:outline hover:outline-zinc-800/75 rounded-[0.5rem] text-sm p-2 text-zinc-400 space-x-1">
            <i class="fa-regular fa-money-bill"></i>
            <span class="hidden md:inline-flex">Баланс</span>
        </a>
        <a href="/profile/person"
            class="hover:outline hover:outline-zinc-800/75 rounded-[0.5rem] text-sm p-2 text-zinc-400 space-x-1">
            <i class="fa-regular fa-palette"></i>
            <span class="hidden md:inline-flex">Персонализация</span>
        </a>
        <a href="/profile/status"
            class="hidden hover:outline hover:outline-zinc-800/75 rounded-[0.5rem] text-sm p-2 text-zinc-400 space-x-1">
            <i class="fa-regular fa-crown"></i>
            <span class="hidden md:inline-flex">Статус</span>
        </a>
        <a href="/profile/settings"
            class="hidden hover:outline hover:outline-zinc-800/75 rounded-[0.5rem] text-sm p-2 text-zinc-400 space-x-1">
            <i class="fa-regular fa-gear"></i>
            <span class="hidden md:inline-flex">Настройки</span>
        </a>
        <a href="/profile/actionlog"
            class="hidden hover:outline hover:outline-zinc-800/75 rounded-[0.5rem] text-sm p-2 text-zinc-400 space-x-1">
            <i class="fa-regular fa-clock"></i>
            <span class="hidden md:inline-flex">Лог действий</span>
        </a>

    </div>

</div>