<div class="grid grid-cols-1 md:grid-cols-2">

  <div class="bg-zinc-950 border border-zinc-900 rounded-lg min-h-24 max-h-32 p-4  relative overflow-visible">
    <div class="flex justify-between">
      <div class="flex-1 flex flex-col justify-between min-w-0">
        <div class="flex justify-between items-end">
          <div class="text-lg font-bold">Достижения: 1/2</div>
          <a href="/?router=profile" class="hidden text-xs text-zinc-400 hover:underline hover:underline-offset-2">
            Все достижения
          </a>
        </div>

        <div
          class="flex gap-2 overflow-x-auto scrollbar-thin scrollbar-purple-400 scrollbar-track-zinc-950 min-w-0 py-2">
          <div>
            <div tabindex="0" data-popover-target="achievement-register"
              class="size-12 rounded-lg border border-zinc-800 shrink-0 flex justify-center items-center text-zinc-400">
              <i class="fa-solid fa-key"></i>
            </div>
            <div id="achievement-register" role="tooltip"
              class="absolute z-1 invisible opacity-0 transition-opacity duration-200 rounded-lg border border-zinc-800 bg-zinc-950 p-3 text-sm max-w-xs">
              <div class="font-semibold mb-1">Регистрация</div>
              <div class="text-zinc-400">Первый вход в систему</div>
            </div>
          </div>
        </div>
      </div>
      <div class="relative shrink-0">
        <div id="chartAdvanced" class="size-24"></div>
        <div class="absolute inset-0 flex justify-center items-center">
          50%
        </div>
      </div>
    </div>

  </div>

</div>