<div class="bg-zinc-950 border border-zinc-900 rounded-2xl p-4 h-32 flex relative overflow-hidden">
    <div class="absolute inset-0 top-0 bg-[url(/app/modules/main/public/assets/img/bg-5.jpg)] bg-cover bg-center">

    </div>
    <div
        class="absolute inset-0 flex items-center gap-4 px-4 bg-linear-to-r from-zinc-950 via-zinc-950/95 to-transparent">
        <div class="size-16 overflow-hidden rounded-full">
            <img src="/?router=skin&mode=mini">
        </div>
        <div>
            <div class="font-semibold text-2xl">
                <?
                #$this->user->login; 
                ?>
            </div>
            <div class="text-sm text-zinc-500">Игрок</div>
        </div>
    </div>
</div>