<div class="h-dvh relative">

  <div class="absolute inset-0 bg-[url('/application/Modules/Auth/Public/img/background.jpg')] bg-cover bg-center">
    <div class="absolute inset-0 bg-black opacity-70"></div>
  </div>



  <div class="absolute inset-0 backdrop-blur flex justify-center items-center">
    <div id="card-login" class="bg-zinc-900 border border-zinc-800 p-8 w-full max-w-xl rounded-2xl shadow-2xl shadow-purple-400/25 backdrop-blur">
      <div class="text-center mb-8">
        <div class="text-2xl font-black text-white uppercase tracking-tighter">
          С возвращением<span class="text-purple-500">.</span>
        </div>
        <span class="text-zinc-400 text-2xs font-bold uppercase tracking-widest">
          Введите данные для входа
        </span>
      </div>

      <form id="formLogin" class="space-y-4">
        <div class="relative group flex items-center">
          <div
            class="absolute left-5 size-6 text-zinc-400 group-focus-within:text-purple-400 transition-colors pointer-events-none z-1">
            <div class="relative">
              <div id="icon-user" class="absolute transition-all duration-700 opacity-100 scale-100">
                <i class="fa-duotone fa-regular fa-user"></i>
              </div>
              <div id="icon-at" class="absolute transition-all duration-700 opacity-0 scale-50">
                <i class="fa-duotone fa-regular fa-at"></i>
              </div>
            </div>
          </div>
          <input type="text" name="login" id="loginInput" placeholder=" "
            class="peer w-full bg-zinc-950 border border-zinc-800 rounded-2xl py-4 pl-12 pr-4 text-white placeholder-transparent outline-none focus:border-purple-400/50 focus:ring-4 focus:ring-purple-400/25 transition-all z-0">
          <label for="loginInput"
            class="absolute left-12 top-1/2 -translate-y-1/2 text-sm text-zinc-400 tracking-widest pointer-events-none transition-all duration-100 z-10
          peer-focus:left-5 peer-focus:top-0 peer-focus:bg-zinc-950 peer-focus:border peer-focus:border-purple-400/50 peer-focus:px-2 peer-focus:py-0.5 peer-focus:rounded-lg peer-focus:text-2xs peer-focus:text-purple-400
          peer-not-placeholder-shown:left-5 peer-not-placeholder-shown:top-0 peer-not-placeholder-shown:bg-zinc-950 peer-not-placeholder-shown:border peer-not-placeholder-shown:border-purple-400/50 peer-not-placeholder-shown:px-2 peer-not-placeholder-shown:py-0.5 peer-not-placeholder-shown:rounded-lg peer-not-placeholder-shown:text-2xs">
            Логин / E-mail
          </label>
        </div>
        <div class="relative group flex items-center">
          <div
            class="absolute left-5 text-zinc-400 group-focus-within:text-purple-400 transition-colors pointer-events-none z-1 size-6">
            <i class="fa-duotone fa-regular fa-lock"></i>
          </div>
          <input type="password" name="password" id="passwordInput" placeholder=" "
            class="peer w-full bg-zinc-950 border border-zinc-800 rounded-2xl py-4 pl-12 pr-4 text-white placeholder-transparent outline-none focus:border-purple-400/50 focus:ring-4 focus:ring-purple-400/25 transition-all z-0">
          <label for="passwordInput"
            class="absolute left-12 top-1/2 -translate-y-1/2 text-sm text-zinc-400 tracking-widest pointer-events-none transition-all duration-100 z-10
          peer-focus:left-5 peer-focus:top-0 peer-focus:bg-zinc-950 peer-focus:border peer-focus:border-purple-400/50 peer-focus:px-2 peer-focus:py-0.5 peer-focus:rounded-lg peer-focus:text-2xs peer-focus:text-purple-400
          peer-not-placeholder-shown:left-5 peer-not-placeholder-shown:top-0 peer-not-placeholder-shown:bg-zinc-950 peer-not-placeholder-shown:border peer-not-placeholder-shown:border-purple-400/50 peer-not-placeholder-shown:px-2 peer-not-placeholder-shown:py-0.5 peer-not-placeholder-shown:rounded-lg peer-not-placeholder-shown:text-2xs">
            Пароль
          </label>
          <button id="showPassword" type="button"
            class="absolute right-5 text-zinc-400 hover:text-purple-400 cursor-pointer transition-colors z-10">
            <i id="icon-show-password" class="fa-duotone fa-regular fa-eye text-base"></i>
          </button>
        </div>
        <!-- <div class="flex justify-between items-center mt-4 ">
          <label class="inline-flex items-center cursor-pointer select-none group gap-0.5">
            <div class="relative">
              <input type="checkbox" name="remember" id="remember" value="" class="sr-only peer">
              <div class="w-9 h-5 bg-zinc-950 rounded-full transition-colors duration-200 
                peer-checked:bg-purple-500 
                group-hover:bg-zinc-800 group-hover:peer-checked:bg-purple-500 peer-checked:shadow-full-md peer-checked:shadow-purple-500/50">
              </div>
              <div class="absolute top-1 left-1 w-3 h-3 bg-zinc-400 rounded-full transition-all duration-200 
                peer-checked:translate-x-4 peer-checked:bg-white">
              </div>
            </div>
            <span class="ms-2 text-sm font-medium text-zinc-400 transition-colors duration-200 group-hover:text-zinc-200">
              Запомнить меня
            </span>
          </label>

        </div> -->
        <div class="flex items-center gap-4 w-full">
          <button id="btnLogin" type="submit"
            class="w-full bg-purple-500 hover:bg-purple-400 font-bold py-4 rounded-2xl transition-all hover:shadow-full-md hover:shadow-purple-400/50 uppercase tracking-widest text-xs active:scale-99 duration-200 flex justify-center items-center gap-3 disabled:opacity-75 disabled:cursor-not-allowed cursor-pointer h-12">
            <span>Авторизоваться</span>
          </button>

          <label class="size-12 shrink-0 flex items-center justify-center ring-1 ring-zinc-800 text-zinc-400 hover:text-zinc-400 hover:ring-purple-400 rounded-2xl transition-all duration-200 cursor-pointer relative select-none group bg-zinc-900
      has-checked:ring-purple-500 has-checked:text-purple-400 has-checked:bg-purple-500/10 has-checked:shadow-full-md has-checked:shadow-purple-400/50 hover:shadow-full-md hover:shadow-purple-400/50 hover:bg-purple-500/10">
            <input type="checkbox" name="remember" id="remember" class="sr-only peer">
            <div class="absolute top-2 right-2 size-1 rounded-full bg-zinc-800 transition-all duration-200 peer-checked:bg-purple-400 peer-checked:shadow-full-sm peer-checked:shadow-purple-400 group-hover:bg-zinc-700"></div>
            <div class="relative flex items-center justify-center size-6 pointer-events-none text-xl transition-all duration-200">
              <i class="fa-duotone fa-regular fa-user -translate-x-0.5 transition-colors duration-200 group-has-checked:text-purple-400/80 group-hover:text-purple-400/80"></i>
              <div class="absolute bottom-0 right-0 translate-x-0.5 translate-y-0.5 size-3.5 bg-zinc-900 rounded-full">
              </div>
              <div class="absolute bottom-0 right-0 translate-x-0.5 translate-y-0.5 size-3.5 flex items-center justify-center rounded-full transition-all duration-200
                bg-zinc-90
                group-has-checked:bg-purple-500/10 group-hover:bg-purple-500/10">
                <i class="fa-solid fa-check text-2xs text-zinc-400 transition-all duration-200 
                group-hover:text-purple-400 
                group-has-checked:text-purple-400 group-has-checked:drop-shadow-[0_0_4px_rgba(208, 140, 100, 1)]"></i>
              </div>
            </div>
          </label>

          <a href="/auth/forgot"
            class="size-12 shrink-0 flex items-center justify-center bg-transparent hover:bg-purple-500/10 ring-1 ring-zinc-800 text-zinc-400 hover:text-purple-400 hover:ring-purple-400 rounded-2xl transition-all hover:shadow-full-md hover:shadow-purple-400/50 duration-200 cursor-pointer relative">
            <div class="relative flex items-center justify-center size-full">
              <i class="fa-thin fa-rotate text-2xl absolute"></i>
              <i class="fa-duotone fa-regular fa-lock text-2xs absolute"></i>
            </div>
          </a>
        </div>
      </form>

      <div class="mt-8 text-center">
        <span class="text-zinc-600 text-sm font-semibold uppercase tracking-wide">
          Нет аккаунта?
          <a href="/auth/register"
            class="text-white hover:text-purple-400 transition-colors ml-1 duration-200">Зарегистрироваться</a>
        </span>
      </div>
    </div>
  </div>
</div>