<table align="center" width="100%" max-width="600" cellpadding="0" cellspacing="0" style="max-width: 600px; margin: 40px auto; background-color: #09090b; border-radius: 0.75rem; overflow: hidden; box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.3), 0 4px 6px -2px rgba(0, 0, 0, 0.2); border-collapse: collapse; color: #e0e0e0;">

  <tr>
    <td style="background-color: #c27aff; padding: 2rem; text-align: center; border-bottom: 1px solid #374151;">
      <img src="https://wisteriamc.ru/public/assets/img/wisteria.PNG" style="height: 72px; margin: auto;">
      <h1 style="margin: 0; font-size: 1.5rem; font-weight: 600; color: #f1f5f9;">Добро пожаловать!</h1>
    </td>
  </tr>

  <tr>
    <td style="padding: 2rem; background-color: #09090b;">
      <h2 style="font-size: 1.25rem; font-weight: 600; color: #f1f5f9; margin-top: 0;">Ваш аккаунт успешно создан</h2>
      <p style="color: #9ca3af; margin: 0.5rem 0;">Приветствуем вас, <?= $login; ?>! Вы сделали первый шаг к увлекательным приключениям на наших серверах. Теперь вы можете войти в свой профиль и настроить его под себя.</p>

      <p style="color: #9ca3af; margin: 0.5rem 0;">Мы отметили ваш первый вход - это значит, что аккаунт активен и готов к использованию.</p>

      <p style="color: #9ca3af; margin: 0.5rem 0; font-style: italic; font-size: 0.75rem;">Если вы не регистрировались - немедленно смените пароль или свяжитесь с поддержкой.</p>

      <a href="https://wisteriamc.ru/porifle/settings" style="display: inline-block; padding: 0.75rem 1.5rem; background-color: #c27aff; color: #f1f5f9; text-decoration: none; border-radius: 0.5rem; font-weight: 500; font-size: 0.875rem; box-shadow: 0 4px 6px rgba(194, 122, 255, 0.2); transition: all 0.2s ease; margin-top: 1rem;">Перейти в настройки</a>
    </td>
  </tr>

  <tr>
    <td style="padding: 1.5rem; text-align: center; background-color: #18181b; color: #6b7280; font-size: 0.875rem; border-top: 1px solid #374151;">
      <p style="margin: 0.5rem 0;">2026 WisteriaMC.</p>
    </td>
  </tr>
</table>