<div class="h-screen relative">

  <div class="absolute inset-0 bg-[url('/public/assets/img/background/background.png')] bg-cover bg-center">
    <div class="absolute inset-0 bg-black opacity-50"></div>
  </div>



  <div class="absolute inset-0 backdrop-blur flex justify-center items-center">
    <div class="bg-purple-950/75 border border-purple-800 p-8 w-full max-w-xl rounded-2xl shadow-2xl shadow-purple-900/75 backdrop-blur">
      <div class="text-center mb-8">
        <div class="text-2xl font-black text-white uppercase tracking-tighter">
          Создать аккаунт<span class="text-purple-500">.</span>
        </div>
        <span class="text-zinc-300 text-2xs font-bold uppercase tracking-widest">
          Присоединяйтесь к нам
        </span>
      </div>

      <form id="formAuth" class="space-y-4">
        <div class="relative group flex items-center">
          <div
            class="absolute left-5 size-6 text-purple-200/50 group-focus-within:text-purple-200 transition-colors pointer-events-none z-1">
            <div class="relative">
              <div id="icon-user" class="absolute transition-all duration-700 opacity-100 scale-100">
                <i class="fa-duotone fa-regular fa-user"></i>
              </div>
            </div>
          </div>
          <input type="text" name="login" id="loginInput" placeholder=" " class="
            peer w-full bg-purple-950 rounded-2xl py-4 
            border border-purple-800 
            pl-12 pr-4 text-white placeholder-transparent outline-none 
            focus:border-purple-400/50
            focus:ring-4 focus:ring-purple-400/25 transition-all z-0 
            focus:shadow-full focus:shadow-purple-400">
          <label for="loginInput" class="
            absolute left-12 top-1/2 -translate-y-1/2
            text-sm text-purple-200/50 tracking-widest pointer-events-none transition-all duration-100 z-1
            peer-not-placeholder-shown:left-5 peer-not-placeholder-shown:top-0 peer-not-placeholder-shown:bg-purple-950 
            peer-not-placeholder-shown:border peer-not-placeholder-shown:border-purple-400/50 peer-not-placeholder-shown:px-2 
            peer-not-placeholder-shown:py-0.5 
            peer-not-placeholder-shown:rounded-lg peer-not-placeholder-shown:text-2xs peer-not-placeholder-shown:text-purple-200
            peer-focus:left-5 peer-focus:top-0
            peer-focus:bg-purple-950
            peer-focus:border peer-focus:border-purple-400/50
            peer-focus:px-2 peer-focus:py-0.5 
            peer-focus:rounded-lg peer-focus:text-2xs peer-focus:text-purple-200
            
          ">
            Логин
          </label>
        </div>
        <div class="relative group flex items-center">
          <div
            class="absolute left-5 size-6 text-purple-200/50 group-focus-within:text-purple-200 transition-colors pointer-events-none z-1">
            <div class="relative">
              <div id="icon-user" class="absolute transition-all duration-700 opacity-100 scale-100">
                <i class="fa-duotone fa-regular fa-at"></i>
              </div>
            </div>
          </div>
          <input type="email" name="email" id="emailInput" placeholder=" " class="
            peer w-full bg-purple-950 rounded-2xl py-4 
            border border-purple-800 
            pl-12 pr-4 text-white placeholder-transparent outline-none 
            focus:border-purple-400/50
            focus:ring-4 focus:ring-purple-400/25 transition-all z-0 
            focus:shadow-full focus:shadow-purple-400">
          <label for="loginInput" class="
            absolute left-12 top-1/2 -translate-y-1/2
            text-sm text-purple-200/50 tracking-widest pointer-events-none transition-all duration-100 z-1
            peer-not-placeholder-shown:left-5 peer-not-placeholder-shown:top-0 peer-not-placeholder-shown:bg-purple-950 
            peer-not-placeholder-shown:border peer-not-placeholder-shown:border-purple-400/50 peer-not-placeholder-shown:px-2 
            peer-not-placeholder-shown:py-0.5 
            peer-not-placeholder-shown:rounded-lg peer-not-placeholder-shown:text-2xs peer-not-placeholder-shown:text-purple-200
            peer-focus:left-5 peer-focus:top-0
            peer-focus:bg-purple-950
            peer-focus:border peer-focus:border-purple-400/50
            peer-focus:px-2 peer-focus:py-0.5 
            peer-focus:rounded-lg peer-focus:text-2xs peer-focus:text-purple-200
            
          ">
            E-mail
          </label>
        </div>
        <div class="relative group flex items-center">
          <div
            class="absolute left-5 size-6 text-purple-200/50 group-focus-within:text-purple-200 transition-colors pointer-events-none z-1">
            <div class="relative">
              <div class="absolute transition-all duration-700 opacity-100 scale-100">
                <i class="fa-duotone fa-regular fa-lock"></i>
              </div>
            </div>
          </div>
          <input type="password" name="password" id="passwordInput" placeholder=" " class="
            peer w-full bg-purple-950 rounded-2xl py-4 
            border border-purple-800 
            pl-12 pr-4 text-white placeholder-transparent outline-none 
            focus:border-purple-400/50
            focus:ring-4 focus:ring-purple-400/25 transition-all z-0 
            focus:shadow-full focus:shadow-purple-400">
          <label for="loginInput" class="
            absolute left-12 top-1/2 -translate-y-1/2
            text-sm text-purple-200/50 tracking-widest pointer-events-none transition-all duration-100 z-1
            peer-not-placeholder-shown:left-5 peer-not-placeholder-shown:top-0 peer-not-placeholder-shown:bg-purple-950 
            peer-not-placeholder-shown:border peer-not-placeholder-shown:border-purple-400/50 peer-not-placeholder-shown:px-2 
            peer-not-placeholder-shown:py-0.5 
            peer-not-placeholder-shown:rounded-lg peer-not-placeholder-shown:text-2xs peer-not-placeholder-shown:text-purple-200
            peer-focus:left-5 peer-focus:top-0
            peer-focus:bg-purple-950
            peer-focus:border peer-focus:border-purple-400/50
            peer-focus:px-2 peer-focus:py-0.5 
            peer-focus:rounded-lg peer-focus:text-2xs peer-focus:text-purple-200
          ">
            Пароль
          </label>
          <button id="showPassword" type="button"
            class="absolute right-5 text-purple-200/50 hover:text-purple-200 cursor-pointer transition-colors z-1">
            <i id="icon-show-password" class="fa-duotone fa-regular fa-eye text-base"></i>
          </button>
        </div>
        <div class="flex items-center gap-4 w-full">
          <button id="btnSubmit" type="submit"
            class="w-full bg-purple-400/50 hover:bg-transparent hover:ring hover:ring-purple-200 font-bold py-4 rounded-2xl transition-all hover:shadow-full-xl hover:shadow-purple-200/50 uppercase tracking-widest text-xs active:scale-99 duration-200 flex justify-center items-center gap-3 disabled:opacity-75 disabled:cursor-not-allowed cursor-pointer h-12">
            <span>Зарегистрироваться</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</div>