<div id="app" class="flex h-screen gap-4 p-4 max-h-screen overflow-hidden">
    <!-- Левый сайдбар: на ПК — w-48, на телефонах — w-16 -->
    <div id="nav-side-left" class="bg-zinc-900/50 border border-zinc-800 rounded-2xl p-4 w-48 shrink-0 flex flex-col">
    </div>

    <div class="flex-1 flex flex-col gap-4 min-h-0">
        <div id="nav-side-top"
            class="bg-zinc-900/70 backdrop-blur-sm border border-zinc-800/50 p-4 rounded-2xl shrink-0 flex justify-between items-center">

        </div>

        <div class="flex flex-1 min-h-0 flex-col md:flex-row gap-4">
            <div id="content" class="flex-1 min-w-0 overflow-y-auto scrollbar-thin"></div>
            <div id="nav-side-right"
                class="bg-zinc-900/50 p-4 rounded-2xl border border-zinc-800 w-48 shrink-0 hidden md:block"></div>
        </div>
    </div>
</div>

