<div id="app" class="flex h-screen gap-4 max-h-screen overflow-hidden md:pt-20 md:pb-4 max-w-8xl w-full mx-auto p-2 md:p-0">
    <div id="navbar" class="fixed top-0 left-0 w-full z-1 px-4 md:px-0"></div>
    <div id="nav-left" class="bg-zinc-950 border border-zinc-900 rounded-2xl p-4 w-16 md:w-48 shrink-0 flex flex-col"></div>
    <div class="flex flex-1 min-h-0 flex-col gap-4">
        <div id="nav-top" class=""></div>
        <div id="content" class="flex-1 min-w-0 overflow-y-auto scrollbar-thin"></div>
    </div>
    <div class="toast-container fixed bottom-0 w-full z-10 p-2 md:max-w-md md:inset-e-0 flex flex-col gap-2"></div>
</div>