<div class="relative md:h-screen overflow-hidden bg-[url('/public/assets/img/background/background.png')] bg-cover bg-center ">
    <div class="absolute inset-0 bg-violet-950/50"></div>
    <div class="absolute -top-40 -left-40 size-150 rounded-full bg-violet-900/50 blur-2xl mix-blend-screen"></div>

    <div class="absolute -bottom-20 -right-20 size-125 rounded-full bg-indigo-900/50 blur-2xl mix-blend-screen"></div>

    <div class="relative z-1 h-full grid grid-cols-1 md:grid-cols-2 max-w-6xl mx-auto py-24 md:py-0">
        <div class="flex flex-col justify-center p-4 md:py-4 gap-4">
            <div class="text-6xl -tracking-wide bg-linear-to-r from-white to-purple-400 bg-clip-text font-exo-black text-transparent py-2">
                Встречайте Techno-Magic!
            </div>
            <div class="flex gap-4">
                <div class="w-1 bg-purple-400 shadow-full-sm shadow-purple-400/50 rounded-full"></div>
                <div class="space-y-2">
                    <div class="text-zinc-200 text-xs md:text-base font-medium leading-relaxed max-w-sm uppercase tracking-wide md:text-left px-2">
                        Новый сервер Techno-Magic уже доступен! Откройте для себя новые горизонты магического мира в техническом сегменте
                    </div>
                    <div class="flex">
                        <div class="bg-purple-800/25 backdrop-blur-xs px-4 py-2 rounded-xl border border-white/25 flex items-center gap-2">
                            <span class="text-2xs text-zinc-200 uppercase tracking-widest">
                                <span class="text-purple-500 font-black">
                                    <?= $usersCount; ?>
                                </span>
                                <?= $this->declension($usersCount, ['пользователь', 'пользователя', 'пользователей']); ?> уже
                                с нами
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="flex gap-4">
                <a href="#" class="px-6 py-4 rounded-md bg-purple-400 hover:bg-purple-400/50 hover:ring-2 hover:ring-purple-400 uppercase text-sm hover:-translate-y-0.5 transition-all duration-200 cursor-pointer hover:shadow-full-xl hover:shadow-blue-400/50">
                    Начать игру</a>
                <a href="#" class="px-6 py-4 rounded-md bg-zinc-950/25 uppercase text-sm border border-zinc-400/25 hover:-translate-y-0.5 transition-all duration-200 cursor-pointer">Новости</a>
            </div>
            <div class="flex gap-4">
                <div class="bg-white/5 border border-white/10 px-4 py-2 rounded-md backdrop-blur-xs">
                    <div class="font-exo-black">1.21.1</div>
                    <div class="text-[8px] uppercase text-zinc-300">Основная версия</div>
                </div>
                <div class="bg-white/5 border border-white/10 px-4 py-2 rounded-md backdrop-blur-xs">
                    <div class="font-exo-black">Techno-Magic</div>
                    <div class="text-[8px] uppercase text-zinc-300">Популярный сервер</div>
                </div>
                <div class="bg-white/5 border border-white/10 px-4 py-2 rounded-md backdrop-blur-xs">
                    <div class="font-exo-black">20 TPC</div>
                    <div class="text-[8px] uppercase text-zinc-300">Стабильные сервера</div>
                </div>
            </div>
        </div>
        <div class="flex justify-center items-center pointer-events-none my-20">
            <div class="relative">

                <div class="md:w-84 md:h-92 w-64 h-72 p-2 border-x border-purple-800 rounded-2xl bg-purple-950/50 backdrop-blur-xs flex justify-center items-center">
                    <div class="size-full bg-[url(/public/assets/img/seasons/season-i-2026.png)] bg-cover bg-center rounded-xl">
                        <span class="hidden">Главный блок</span>
                    </div>
                </div>
                <div class="absolute md:size-42 size-24 md:-bottom-8 md:-left-12 -bottom-2 -left-16 border-x border-purple-800 rounded-2xl bg-purple-950/50 backdrop-blur-xs -rotate-15 flex justify-center items-center p-2 shadow-lg shadow-purple-950">
                    <div class="size-full bg-[url(/public/assets/img/seasons/season-i-2026-1.png)] bg-cover bg-center rounded-xl">
                        <span class="hidden">Левый нижний блок</span>
                    </div>
                </div>
                <div class="absolute md:size-42 size-24 md:-top-8 md:-right-12 -top-4 -right-8 border-x border-purple-800 rounded-2xl bg-purple-950/50 backdrop-blur-xs rotate-25 flex justify-center items-center p-2 shadow-lg shadow-purple-950">
                    <div class="size-full bg-[url(/public/assets/img/seasons/season-i-2026-2.png)] bg-cover bg-center rounded-xl">
                        <span class="hidden">Правый верхний блок</span>
                    </div>
                </div>
                <div class="absolute min-h-32 max-w-2xs md:w-full md:-right-32 md:-bottom-8 -right-16 -bottom-9 border-x border-purple-800 p-4 bg-linear-to-br from-purple-950/50 to-pink-950/50 rounded-2xl backdrop-blur-xs shadow-full shadow-purple-950">
                    <div class="text-xs uppercase font-bold text-purple-300 tracking-widest">Новый сезон</div>
                    <div class="text-md uppercase font-bold text-purple-100">Открытие сезона 2026</div>
                    <div class="mt-2 text-xs font-medium text-purple-200">Успейте принять участие в главном сезоне этого года! Битвы с боссами, ценные награды и многое другое</div>
                </div>
            </div>
        </div>
    </div>
</div>