<div
    class="h-svh bg-[url(/application/Modules/Main/Public/assets/img/banner-3.png)] bg-cover bg-center relative overflow-hidden">
    <div class="absolute inset-0 bg-linear-to-t from-zinc-950 to-transparent backdrop-blur-xs md:backdrop-blur-none">
    </div>
    <svg viewBox="0 0 1000 200" preserveAspectRatio="none" class="block w-[200%] h-32 left-0 -bottom-2 absolute">
        <path id="wave-back" class="fill-black opacity-50"
            d="M0,100 C125,60 375,140 500,100 C625,60 875,140 1000,100 L1000,200 L0,200 Z" />
        <path id="wave-front" class="fill-black"
            d="M0,100 C125,50 375,150 500,100 C625,50 875,150 1000,100 L1000,200 L0,200 Z" />
    </svg>

    <div class="absolute inset-0 flex flex-col">

        <div class="flex flex-1 flex-col items-center justify-center">
            <div class="relative size-48 md:size-64 flex justify-center items-center">
                <div class="size-48 md:size-64 overflow-hidden rounded-full grid grid-cols-2 blur-3xl rotate-45">
                    <div class="bg-purple-400 size-full"></div>
                    <div class="bg-green-400 size-full"></div>
                </div>
                <div class="absolute flex justify-center items-center">
                    <div class="size-32 md:size-48 overflow-hidden">
                        <img src="/public/assets/img/logo.PNG">
                    </div>
                </div>
                <div class="absolute w-full -bottom-2 md:-bottom-6 flex justify-center items-end">
                    <div class="">
                        <img src="/public/assets/img/wisteria.PNG" class="">
                    </div>
                </div>

            </div>
        </div>
        <div class="w-full max-w-8xl mx-auto flex flex-col md:flex-row justify-between items-center md:items-end pb-28">
            <div class="max-w-3xl w-full">
                <div
                    class="text-4xl text-center md:text-left font-black text-white uppercase tracking-tighter mb-4 shadow-violet-500/20">
                    Скоро<span class="text-purple-400">...</span>
                </div>
                <div
                    class="flex flex-col md:flex-row md:justify-between gap-8 md:items-center border-l-2 border-violet-500/30 md:pl-6 ml-1">
                    <div class="space-y-2">
                        <p
                            class="text-zinc-300 text-sm md:text-base font-medium leading-relaxed max-w-sm uppercase tracking-wide text-center md:text-left px-4">
                            Присоединяйся к нам! Строй механизмы, ищи следы древней магии и сражайся за титул лучшего в
                            эпических PvP-сражениях.
                        </p>
                        <div class="flex flex-wrap justify-center md:justify-start gap-x-4 gap-y-1">
                            <span
                                class="text-2xs text-zinc-300 font-bold uppercase tracking-widest flex items-center gap-1.5">
                                <i class="fa-duotone fa-regular fa-microchip text-blue-400"></i> Hi-Tech
                            </span>
                            <span
                                class="text-2xs text-zinc-300 font-bold uppercase tracking-widest flex items-center gap-1.5">
                                <i class="fa-duotone fa-regular fa-wand-magic-sparkles text-violet-400"></i> Magic
                            </span>
                            <span
                                class="text-2xs text-zinc-300 font-bold uppercase tracking-widest flex items-center gap-1.5">
                                <i class="fa-duotone fa-regular fa-swords text-red-400"></i> Survival
                            </span>
                        </div>
                    </div>

                </div>
            </div>

            <div class="flex flex-col items-end gap-4">
                <div class="text-right hidden md:block">
                    <span class="text-xs text-zinc-200 font-bold uppercase tracking-widest block mb-1">
                        Предворительная регистрация
                    </span>
                    <div class="h-0.5 w-48 ml-auto bg-linear-to-r from-transparent to-purple-500 rounded-r-full"></div>
                </div>

                <a href="/auth"
                    class="group relative flex justify-center items-center gap-4 bg-purple-500 w-full h-14 rounded-lg uppercase tracking-[0.1rem] font-bold shadow-full-lg shadow-purple-500/50 hover:shadow-full-2xl hover:shadow-purple-400/75 hover:bg-purple-400 transition-all duration-200">
                    <div>
                        <span class="relative text-lg">Регистрация</span>
                        <i class="fa-duotone fa-regular fa-arrow-right text-lg transition-transform group-hover:translate-x-1"></i>
                    </div>
                </a>

                <!-- <a href="/auth"
                    class="group/btn relative flex items-center gap-6 text-white bg-purple-400 hover:bg-purple-500 px-12 py-5 mt-4 md:mt-0 rounded-2xl text-sm font-black transition-all shadow-full-lg shadow-purple-400 hover:shadow-full-xl hover:shadow-purple-400 active:scale-95 uppercase tracking-[0.2em]">
                    <span class="relative text-lg">Регистрация</span>
                    <i
                        class="fa-duotone fa-regular fa-arrow-right text-lg transition-transform group-hover/btn:translate-x-1"></i>
                    <div
                        class="absolute inset-0 rounded-2xl bg-linear-to-tr from-white/20 to-transparent opacity-0 group-hover/btn:opacity-100 transition-opacity">
                    </div>
                </a> -->

                <div class="w-full flex justify-center">
                    <div
                        class="bg-black/40 backdrop-blur-md px-4 py-2 rounded-xl border border-white/5 flex items-center gap-3">
                        <!-- <div class="flex -space-x-2">
                          <div class="w-6 h-6 rounded-md border border-zinc-800 bg-zinc-700"
                            style="background: url('/?router=skin&user=NiRBES&mode=mini'); background-size: cover;">
                          </div>
                          <div class="w-6 h-6 rounded-md border border-zinc-800 bg-zinc-700"
                            style="background: url('/?router=skin&user=Goddessfox&mode=mini'); background-size: cover;">
                          </div>
                          <div class="w-6 h-6 rounded-md border border-zinc-800 bg-zinc-700"
                            style="background: url('/?router=skin&user=Yuki&mode=mini'); background-size: cover;">
                          </div>
                        </div> -->
                        <span class="text-2xs font-bold text-zinc-300 uppercase tracking-widest">
                            <span class="text-purple-500">
                                <?= $usersCount; ?>
                            </span>
                            <?= $this->declension($usersCount, ['пользователь', 'пользователя', 'пользователей']); ?> уже
                            с нами
                        </span>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>