<div id="{id}"
  class="relative hidden opacity-0 transition-all duration-300 ease-linear backdrop-blur-md rounded-2xl border {border} {background} shadow-sm overflow-hidden {ring}"
  role="alert">
  <div class="flex flex-col p-2">
    <div class="flex items-center gap-2">
      <div class="flex items-center justify-center shrink-0 size-8 {block_icon} backdrop-blur-xs rounded-xl">
        <i class="{icon}"></i>
      </div>
      <div class="flex justify-between items-center w-full border-b border-white/25">
        <div class="font-bold text-sm tracking-tight">
          {title}
        </div>
        <div class="flex pb-2 gap-2 pr-2">
          <button type="button"
            class="js-clone-btn flex items-center justify-center size-5 rounded-md text-zinc-400 transition-colors cursor-pointer">
            <i class="fa-duotone fa-regular fa-clone text-xs"></i>
          </button>

          <button type="button" data-dismiss-target="#{id}"
            class="flex items-center justify-center size-5 rounded-lg text-zinc-400 transition-colors cursor-pointer">
            <i class="fa-duotone fa-regular fa-xmark text-xs"></i>
          </button>
        </div>
      </div>
    </div>

    <div class="text-xs overflow-x-hidden overflow-y-auto w-full max-h-64 p-2 pl-10 break-all">
      {message}
    </div>
  </div>

  <div class="absolute bottom-0 left-0 w-full h-px {bar_b}">
    <div id="{id}-progress" class="h-full transition-all duration-50 ease-linear shadow-full-sm {shadow} {bar_t}"
      style="width: 100%"></div>
  </div>
</div>